# Clean Catagorical dataset

## Creating dataset

In [83]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import shap

In [90]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Name': ['Ayesha', 'Rahim', 'Sumi', None, 'Kamal', 'Nila', None],
    'Age': [23, 27, None, 22, 29, None, 24],
    'Gender': ['Female', 'Male', 'Female', 'Male', None, 'Female', 'Male'],
    'Salary': [30000, None, 28000, 35000, None, 31000, 29500],
    'City': ['Dhaka', 'Sylhet', None, 'Khulna', 'Dhaka', None, 'Rajshahi']
})

In [91]:
data

     Name   Age  Gender   Salary      City
0  Ayesha  23.0  Female  30000.0     Dhaka
1   Rahim  27.0    Male      NaN    Sylhet
2    Sumi   NaN  Female  28000.0      None
3    None  22.0    Male  35000.0    Khulna
4   Kamal  29.0    None      NaN     Dhaka
5    Nila   NaN  Female  31000.0      None
6    None  24.0    Male  29500.0  Rajshahi

## Name of the catagorical value

In [92]:
cat_cols = data.select_dtypes(exclude = np.number).columns.tolist()

## Find out the number of missing value

In [93]:
data[cat_cols].isna().sum()

Name      2
Gender    1
City      2
dtype: int64

## Filling dataset

### Filling dataset with mode(most occuring number)

In [88]:
'''for col in cat_cols:
  data[col].fillna(data[col].mode()[0], inplace=True)'''

'for col in cat_cols1:\n  data1[col].fillna(data1[col].mode()[0], inplace=True)'

In [89]:
#data[cat_cols1].isna().sum()

### Fill the dataset with "Unknown"

Good when you don't want to assume anything. ML pipelines use "Unknown" as a best practice especially in real-world dataset

In [94]:
for col in cat_cols:
    data[col].fillna("Unknown", inplace=True)

/tmp/ipython-input-2771032771.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna("Unknown", inplace=True)

In [98]:
data[cat_cols].isna().sum()

Name      0
Gender    0
City      0
dtype: int64

In [97]:
data

      Name   Age   Gender   Salary      City
0   Ayesha  23.0   Female  30000.0     Dhaka
1    Rahim  27.0     Male      NaN    Sylhet
2     Sumi   NaN   Female  28000.0   Unknown
3  Unknown  22.0     Male  35000.0    Khulna
4    Kamal  29.0  Unknown      NaN     Dhaka
5     Nila   NaN   Female  31000.0   Unknown
6  Unknown  24.0     Male  29500.0  Rajshahi

## Fix inconsistent text

In [101]:
#Remove space
data[col]= data[col].str.strip()

In [102]:
#Convert to all lower or upper
data[col] = data[col].str.lower()

## Droping the missing column

### Drop only catagorical missing row

In [105]:
data = data.dropna(subset=cat_cols)
#Or, just the specific column
data = data.dropna(subset=["Gender", "Age"])

### drop all rows whih any missing value

In [106]:
data = data.dropna()